version: "3.5"
services:

  app:
    build:
      context: .
    expose:
      - 3000
    container_name: plex-restarter
    image: ghcr.io/nicholasodonnell/plex-restarter:latest
    networks:
      - plex-restarter

networks:
  plex-restarter:
    driver: bridge
    name: plex-restarter
