version: "3.5"
services:

  app:
    build:
      target: dev
    environment:
      - "RESTART_COMMAND=exit 0"
    image: ghcr.io/nicholasodonnell/plex-restarter:dev
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./:/app
      - node-modules:/app/node_modules

volumes:
  node-modules:
