version: "3.5"
services:

  app:
    build:
      target: dev
    env_file:
      - .env
    image: ghcr.io/nicholasodonnell/plex-restarter:dev
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - node-modules:/app/node_modules

volumes:
  node-modules:
